select TRANSACTION_HISTORY.ITEM,
       ITEM.DESCRIPTION,
       sum(TRANSACTION_HISTORY.QUANTITY, 12, 'this is a test')
from TRANSACTION_HISTORY
     join ITEM on ITEM.COMPANY = TRANSACTION_HISTORY.COMPANY
                  and ITEM.ITEM = TRANSACTION_HISTORY.ITEM
     join ITEM on ITEM.COMPANY = TRANSACTION_HISTORY.COMPANY
                  and ITEM.ITEM = TRANSACTION_HISTORY.ITEM
where TRANSACTION_HISTORY.TRANSACTION_TYPE = 120
      and (
            TRANSACTION_HISTORY.WORK_TYPE = 'Standard Tote Pick'
            or TRANSACTION_HISTORY.WORK_TYPE = 'Standard Case Pick'
      )
      and cast(TRANSACTION_HISTORY.DATE_TIME_STAMP as date) = '2020-07-27'
      and TRANSACTION_HISTORY.DIRECTION = 'To'
             
      -- grouping        
group by TRANSACTION_HISTORY.ITEM,
         ITEM.DESCRIPTION, -- desc   
         ITEM.DATE_TIME_STAMP
order by sum(TRANSACTION_HISTORY.QUANTITY /*quant*/) desc