export const TopLevelKeywords = [
    'add',
    'after',
    'alter column',
    'alter table',
    'delete from',
    'drop table',
    'else',
    'except',
    'fetch first',
    'from',
    'go',
    'group by',
    'having',
    'insert into',
    'insert',
    'intersect',
    'into',
    'limit',
    'modify',
    'order by',
    'select',
    'set current schema',
    'set schema',
    'set',
    'then',
    'union all',
    'union',
    'update',
    'values',
    'when',
    'where',
];

export const BlockKeywords = [
    { open: 'begin', close: 'end' },
    { open: 'case', close: 'end' },
];

export const NewLineKeywords = [
    'and',
    'cross apply',
    'cross join',
    'full join',
    'inner join',
    'join',
    'left join',
    'left outer join',
    'or',
    'outer apply',
    'outer join',
    'right join',
    'right outer join',
    'xor',
];

export const IndentBlockKeywords = [
    { open: 'on', close: 'cross apply' },
    { open: 'on', close: 'cross join' },
    { open: 'on', close: 'full join' },
    { open: 'on', close: 'inner join' },
    { open: 'on', close: 'join' },
    { open: 'on', close: 'left join' },
    { open: 'on', close: 'left outer join' },
    { open: 'on', close: 'outer apply' },
    { open: 'on', close: 'outer join' },
    { open: 'on', close: 'right join' },
    { open: 'on', close: 'right outer join' },
];

export const Keywords = [
    'add',
    'all',
    'alter',
    'and',
    'any',
    'as',
    'asc',
    'authorization',
    'backup',
    'begin',
    'between',
    'bigint',
    'binary',
    'bit',
    'break',
    'browse',
    'bulk',
    'by',
    'cascade',
    'case',
    'char',
    'check',
    'checkpoint',
    'close',
    'clustered',
    'coalesce',
    'collate',
    'column',
    'commit',
    'compute',
    'constraint',
    'contains',
    'containstable',
    'continue',
    'convert',
    'create',
    'cross',
    'current_date',
    'current_time',
    'current_timestamp',
    'current_user',
    'current',
    'cursor',
    'database',
    'date',
    'datetime',
    'datetime2',
    'datetimeoffset',
    'day',
    'dayofyear',
    'dbcc',
    'deallocate',
    'decimal',
    'declare',
    'default',
    'delete',
    'deny',
    'desc',
    'disk',
    'distinct',
    'distributed',
    'double',
    'drop',
    'dump',
    'else',
    'end',
    'errlvl',
    'escape',
    'except',
    'exec',
    'execute',
    'exists',
    'exit',
    'external',
    'fetch',
    'file',
    'fillfactor',
    'float',
    'for',
    'foreign',
    'freetext',
    'freetexttable',
    'from',
    'full',
    'function',
    'geography',
    'geometry',
    'goto',
    'grant',
    'group',
    'having',
    'hierarchyid',
    'holdlock',
    'hour',
    'identity_insert',
    'identity',
    'identitycol',
    'if',
    'image',
    'in',
    'index',
    'inner',
    'insert',
    'int',
    'intersect',
    'into',
    'is',
    'join',
    'key',
    'kill',
    'left',
    'like',
    'lineno',
    'load',
    'merge',
    'microsecond',
    'millisecond',
    'minute',
    'money',
    'month',
    'nanosecond',
    'national',
    'nchar',
    'nocheck',
    'nonclustered',
    'not',
    'ntext',
    'null',
    'nullif',
    'numeric',
    'nvarchar',
    'of',
    'off',
    'offsets',
    'on',
    'open',
    'opendatasource',
    'openquery',
    'openrowset',
    'openxml',
    'option',
    'or',
    'order',
    'outer',
    'over',
    'percent',
    'pivot',
    'plan',
    'precision',
    'primary',
    'print',
    'proc',
    'procedure',
    'public',
    'quarter',
    'raiserror',
    'read',
    'readtext',
    'real',
    'reconfigure',
    'references',
    'replication',
    'restore',
    'restrict',
    'return',
    'revert',
    'revoke',
    'right',
    'rollback',
    'rowcount',
    'rowguidcol',
    'rowversion',
    'rule',
    'save',
    'schema',
    'second',
    'securityaudit',
    'select',
    'semantickeyphrasetable',
    'semanticsimilaritydetailstable',
    'semanticsimilaritytable',
    'session_user',
    'set',
    'setuser',
    'shutdown',
    'smalldatetime',
    'smallint',
    'smallmoney',
    'some',
    'sql_variant',
    'statistics',
    'system_user',
    'table',
    'tablesample',
    'text',
    'textsize',
    'then',
    'time',
    'tinyint',
    'to',
    'top',
    'tran',
    'transaction',
    'trigger',
    'truncate',
    'try_convert',
    'tsequal',
    'union',
    'unique',
    'uniqueidentifier',
    'unpivot',
    'update',
    'updatetext',
    'use',
    'user',
    'values',
    'varbinary',
    'varchar',
    'varying',
    'view',
    'waitfor',
    'week',
    'when',
    'where',
    'while',
    'with',
    'within group',
    'writetext',
    'xml',
    'year',
];